-- 1 - 1000 in view
-- view with count

IF EXISTS(
	SELECT * FROM sys.views
	WHERE [name] = 'SERIES' AND
		schema_id = SCHEMA_ID('dbo'))
	DROP VIEW SERIES;

GO
CREATE VIEW SERIES AS
	WITH Srs(a) AS
		(SELECT 1
		UNION ALL
		SELECT a+1 
			FROM Srs 
			WHERE a < 1027)
	SELECT * FROM Srs;
GO

SELECT * FROM SERIES
	OPTION (MAXRECURSION 0);

IF EXISTS(
	SELECT * FROM sys.views
	WHERE [name] = 'INSERT_COUNT' AND
		schema_id = SCHEMA_ID('dbo'))
	DROP VIEW INSERT_COUNT;

GO
CREATE VIEW INSERT_COUNT AS
	SELECT CUSTOMER.customer_id AS customer
			FROM CUSTOMER
			WHERE CUSTOMER.customer_id 
				in (SELECT 200 + COUNT(customer_id) FROM CUSTOMER)
GO

BEGIN TRAN;

SELECT * FROM CUSTOMER;

INSERT INTO INSERT_COUNT
	VALUES(220);

SELECT * FROM CUSTOMER;

ROLLBACK;