USE CELLULAR;

GO

IF OBJECT_ID ('dbo.PROC_TABLE', 'U') IS NOT NULL
	DROP TABLE PROC_TABLE;

GO

CREATE TABLE PROC_TABLE
	(
		[LoginName] NVARCHAR(MAX),
		[UserName] NVARCHAR(MAX),
		[when] DATETIME,
		[proc] NVARCHAR(MAX)
	);

GO

IF EXISTS (SELECT * FROM sys.all_objects WHERE type = 'TR' AND name = 'PROC_TRACK')
	DROP TRIGGER PROC_TRACK
		ON DATABASE;

GO

-- User, when, what procedure on CREATE_PROCEDURE
CREATE TRIGGER PROC_TRACK
	ON DATABASE
	AFTER CREATE_PROCEDURE
	AS
	BEGIN
		INSERT INTO PROC_TABLE
			VALUES 
			(
				(SELECT EVENTDATA().value('(/EVENT_INSTANCE/LoginName)[1]', 'NVARCHAR(MAX)')),
				(SELECT EVENTDATA().value('(/EVENT_INSTANCE/UserName)[1]', 'NVARCHAR(MAX)')),
				(SELECT EVENTDATA().value('(/EVENT_INSTANCE/PostTime)[1]', 'DATETIME')), 
				(SELECT EVENTDATA().value('(/EVENT_INSTANCE/ObjectName)[1]', 'NVARCHAR(MAX)'))
			);
	END

GO

BEGIN TRANSACTION;

SELECT * FROM PROC_TABLE;

GO

CREATE PROCEDURE TEST_PROC
	AS
	BEGIN
		SELECT * FROM CONNECTION;
	END

GO

SELECT * FROM PROC_TABLE;

ROLLBACK TRANSACTION;