USE CELLULAR;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

BEGIN TRANSACTION;

UPDATE CUSTOMER SET
	[name] = [name]
	WHERE customer_id = 200;

UPDATE JOB SET
	[function] = [function]
	WHERE job_id = 400;

ROLLBACK;