USE CELLULAR;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

BEGIN TRANSACTION;

UPDATE JOB SET
	[function] = [function]
	WHERE job_id = 400;

WAITFOR DELAY '00:00:05';

UPDATE CUSTOMER SET
	[name] = [name]
	WHERE customer_id = 200;

ROLLBACK;