USE CELLULAR;

DROP LOGIN test;
DROP USER test;

CREATE LOGIN test WITH PASSWORD = '111';
CREATE USER test FOR LOGIN test;

GRANT SELECT, INSERT, UPDATE ON JOB TO test;

BEGIN TRANSACTION;
EXECUTE AS USER = 'test';

SELECT * FROM JOB;

INSERT INTO JOB
	values(410, N'машинист');

UPDATE JOB
	SET job_id = 420
	WHERE [function] = N'машинист';

SELECT * FROM EMPLOYEE;

REVERT;
ROLLBACK;